name: Scheduled Temperature Calculation

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openmeteo-requests
          pip install requests-cache retry-requests numpy pandas
          pip install pandas requests-cache retry-requests openmeteo-requests

      - name: Run Python script
        run: |
          python temperatura.py
