name: Executar Python i pujar JSON cada dia a les 23:59

on:
  schedule:
    - cron: "59 23 * * *"  # Cada día a las 23:59
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Clonació del repositori
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configuració de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instal·lació de les dependències
        run: |
          pip install --upgrade pip
          pip install openmeteo-requests pandas requests requests-cache retry_requests

      - name: Execució del script de temperatures
        run: python temeperaturas.py

      - name: Llistat de fitxers JSON generats
        run: ls -l temp_*.json || echo "No s'han generat fitxers .json"

      - name: Configuració de Git
        run: |
          git config user.name "github-actions[bot]"
          git config.user.email "github-actions[bot]@users.noreply.github.com"

      - name: Afegir i commitar fitxers JSON
        run: |
          git add temp_*.json
          git commit -m "Afegit fitxer JSON generat per GitHub Actions [skip ci]" || echo "No hi ha canvis per commitar"

      - name: Configuració del remote per pujar canvis
        run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Pujar els canvis al repositori
        run: git push
