name: Scheduled Temperature Calculation

on:
  push:
    branches: [ main, develop ]

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests-cache retry-requests openmeteo-requests

      - name: Run Python script
        run: |
          python calculo_temperaturas.py

      - name: Add JSON file to repository
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://$GITHUB_TOKEN@github.com/${{ github.repository }}.git
          git add temp_*.json
          git commit -m "Auto: Añadir fichero JSON con temperaturas"
          git push origin HEAD:${{ github.ref_name }}
